---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  labels:
    name: zookeeper-1
spec:
  type: NodePort
  selector:
    component: zookeeper
    ensemble: zookeeper
    server-id: "1"
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 30101
  - name: peer
    port: 2888
    targetPort: 2888
  - name: election
    port: 3888
    targetPort: 3888
---
kind: Pod
apiVersion: v1
metadata:
  name: zookeeper-1
  labels:
    component: zookeeper
    ensemble: zookeeper
    server-id: "1"
spec:
  containers:
    - name: "server"
      image: "everpeace/zookeeper"
      env:
      - name: "SERVER_ID"
        value: "1"
      - name: "MAX_SERVERS"
        value: "3"
      - name: "ENSEMBLE_NAME"
        value: "zookeeper"
      ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
  labels:
    name: zookeeper-2
spec:
  type: NodePort
  selector:
    component: zookeeper
    ensemble: zookeeper
    server-id: "2"
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 30102
  - name: peer
    port: 2888
    targetPort: 2888
  - name: election
    port: 3888
    targetPort: 3888
---
kind: Pod
apiVersion: v1
metadata:
  name: zookeeper-2
  labels:
    component: zookeeper
    ensemble: zookeeper
    server-id: "2"
spec:
  containers:
    - name: "server"
      image: "everpeace/zookeeper"
      env:
      - name: "SERVER_ID"
        value: "2"
      - name: "MAX_SERVERS"
        value: "3"
      - name: "ENSEMBLE_NAME"
        value: "zookeeper"
      ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  labels:
    name: zookeeper-3
spec:
  type: NodePort
  selector:
    component: zookeeper
    ensemble: zookeeper
    server-id: "3"
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 30103
  - name: peer
    port: 2888
    targetPort: 2888
  - name: election
    port: 3888
    targetPort: 3888
---
kind: Pod
apiVersion: v1
metadata:
  name: zookeeper-3
  labels:
    component: zookeeper
    ensemble: zookeeper
    server-id: "3"
spec:
  containers:
    - name: "server"
      image: "everpeace/zookeeper"
      env:
      - name: "SERVER_ID"
        value: "3"
      - name: "MAX_SERVERS"
        value: "3"
      - name: "ENSEMBLE_NAME"
        value: "zookeeper"
      ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
